# Generated by Django 3.2.15 on 2022-08-13 01:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PeliMundo', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pelicula',
            old_name='categoria',
            new_name='genero',
        ),
    ]
